// <auto-generated />
using System;
using InternalResourceBookingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternalResourceBookingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203142238_CreatedDbSchema")]
    partial class CreatedDbSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternalResourceBookingSystem.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedBy = "Thandi Mokoena",
                            EndTime = new DateTime(2025, 11, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Sprint Planning",
                            ResourceId = 1,
                            StartTime = new DateTime(2025, 11, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BookedBy = "Sipho Ngubane",
                            EndTime = new DateTime(2025, 11, 25, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Client Visit - Cape Town",
                            ResourceId = 6,
                            StartTime = new DateTime(2025, 11, 25, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BookedBy = "Lerato Khumalo",
                            EndTime = new DateTime(2025, 11, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Offsite Development Sprint",
                            ResourceId = 10,
                            StartTime = new DateTime(2025, 11, 18, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BookedBy = "Lisa Naidoo",
                            EndTime = new DateTime(2025, 12, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Executive Leadership Meeting",
                            ResourceId = 3,
                            StartTime = new DateTime(2025, 12, 3, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BookedBy = "Dev Team",
                            EndTime = new DateTime(2025, 12, 3, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Product Demo Rehearsal",
                            ResourceId = 1,
                            StartTime = new DateTime(2025, 12, 3, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BookedBy = "Events Team",
                            EndTime = new DateTime(2025, 12, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Year-End Townhall Setup",
                            ResourceId = 12,
                            StartTime = new DateTime(2025, 12, 4, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BookedBy = "HR Department",
                            EndTime = new DateTime(2025, 12, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Team Building Gaming Night",
                            ResourceId = 18,
                            StartTime = new DateTime(2025, 12, 5, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BookedBy = "Finance Team",
                            EndTime = new DateTime(2025, 12, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "2026 Budget Review",
                            ResourceId = 2,
                            StartTime = new DateTime(2025, 12, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BookedBy = "Field Operations",
                            EndTime = new DateTime(2025, 12, 4, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Site Visit - Durban",
                            ResourceId = 7,
                            StartTime = new DateTime(2025, 12, 4, 7, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BookedBy = "Design Team",
                            EndTime = new DateTime(2025, 12, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Quick Brainstorm",
                            ResourceId = 4,
                            StartTime = new DateTime(2025, 12, 6, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BookedBy = "Nomsa Zuma",
                            EndTime = new DateTime(2025, 12, 19, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Training Workshop Prep",
                            ResourceId = 10,
                            StartTime = new DateTime(2025, 12, 15, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BookedBy = "Marketing Team",
                            EndTime = new DateTime(2025, 12, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Product Launch Party",
                            ResourceId = 13,
                            StartTime = new DateTime(2025, 12, 20, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BookedBy = "Wellness Committee",
                            EndTime = new DateTime(2025, 12, 9, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Stress Relief Session",
                            ResourceId = 19,
                            StartTime = new DateTime(2025, 12, 9, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BookedBy = "Early Risers Club",
                            EndTime = new DateTime(2025, 12, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Coffee Tasting Morning",
                            ResourceId = 20,
                            StartTime = new DateTime(2025, 12, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            BookedBy = "Sales Team",
                            EndTime = new DateTime(2025, 12, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Q4 Sales Planning",
                            ResourceId = 1,
                            StartTime = new DateTime(2025, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            BookedBy = "HR Team",
                            EndTime = new DateTime(2025, 12, 18, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Performance Reviews",
                            ResourceId = 3,
                            StartTime = new DateTime(2025, 12, 18, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            BookedBy = "Logistics",
                            EndTime = new DateTime(2025, 12, 23, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Year-End Deliveries",
                            ResourceId = 6,
                            StartTime = new DateTime(2025, 12, 23, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            BookedBy = "Finance",
                            EndTime = new DateTime(2025, 12, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Annual Report Printing",
                            ResourceId = 15,
                            StartTime = new DateTime(2025, 12, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            BookedBy = "Creative Director",
                            EndTime = new DateTime(2026, 1, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Brand Video Project",
                            ResourceId = 11,
                            StartTime = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            BookedBy = "Board of Directors",
                            EndTime = new DateTime(2025, 12, 19, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Year-End Board Meeting",
                            ResourceId = 3,
                            StartTime = new DateTime(2025, 12, 19, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("InternalResourceBookingSystem.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            Description = "10-seater with projector & whiteboard",
                            IsAvailable = true,
                            Location = "2nd Floor, West Wing",
                            Name = "Meeting Room Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 8,
                            Description = "8-seater with video conferencing",
                            IsAvailable = true,
                            Location = "3rd Floor, East Wing",
                            Name = "Meeting Room Beta"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 16,
                            Description = "Premium boardroom for 16 people",
                            IsAvailable = true,
                            Location = "1st Floor, Admin Block",
                            Name = "Boardroom Executive"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            Description = "Quick 4-person collaboration space",
                            IsAvailable = true,
                            Location = "4th Floor, Open Area",
                            Name = "Huddle Room 1"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 30,
                            Description = "30-seater training facility",
                            IsAvailable = false,
                            Location = "Ground Floor, Training",
                            Name = "Training Room"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 4,
                            Description = "Compact sedan - White",
                            IsAvailable = true,
                            Location = "Parking Bay A1",
                            Name = "Toyota Corolla (Car 1)"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 5,
                            Description = "Double cab for site visits",
                            IsAvailable = true,
                            Location = "Parking Bay B3",
                            Name = "Ford Ranger (Bakkie)"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 15,
                            Description = "15-seater passenger van",
                            IsAvailable = false,
                            Location = "Garage Level 2",
                            Name = "Mercedes Sprinter Van"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 2,
                            Description = "Small delivery bakkie",
                            IsAvailable = true,
                            Location = "Loading Bay",
                            Name = "Nissan NP200 (Delivery)"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 1,
                            Description = "i7, 32GB RAM, 1TB SSD",
                            IsAvailable = true,
                            Location = "IT Storage Room",
                            Name = "Dell Laptop Pro"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 1,
                            Description = "M2 Max for design/video",
                            IsAvailable = false,
                            Location = "Creative Team Locker",
                            Name = "MacBook Pro 16"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 1,
                            Description = "Portable 4K projector",
                            IsAvailable = true,
                            Location = "AV Cupboard",
                            Name = "Projector Epson 4K"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 1,
                            Description = "Portable Bluetooth speakers",
                            IsAvailable = true,
                            Location = "Events Store",
                            Name = "JBL Party Speakers"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 4,
                            Description = "Wireless microphone kit",
                            IsAvailable = true,
                            Location = "AV Cupboard",
                            Name = "Wireless Mic Set (4)"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 1,
                            Description = "HP Color LaserJet - A3 capable",
                            IsAvailable = true,
                            Location = "Print Room, 2nd Floor",
                            Name = "Large Color Printer"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 1,
                            Description = "Electric height-adjustable desk",
                            IsAvailable = true,
                            Location = "Furniture Storage",
                            Name = "Standing Desk"
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 1,
                            Description = "Portable Unlimited data router",
                            IsAvailable = false,
                            Location = "IT Desk",
                            Name = "4G Mobile Hotspot"
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 6,
                            Description = "Gaming setup in chill room",
                            IsAvailable = true,
                            Location = "Recreation Room, 5th Floor",
                            Name = "Xbox Series X + TV"
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 1,
                            Description = "Full-body massage chair",
                            IsAvailable = true,
                            Location = "Wellness Room",
                            Name = "Massage Chair"
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 1,
                            Description = "Professional espresso machine",
                            IsAvailable = true,
                            Location = "Kitchen, 4th Floor",
                            Name = "Coffee Machine (Barista)"
                        });
                });

            modelBuilder.Entity("InternalResourceBookingSystem.Models.Booking", b =>
                {
                    b.HasOne("InternalResourceBookingSystem.Models.Resource", "Resource")
                        .WithMany("Bookings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("InternalResourceBookingSystem.Models.Resource", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
